import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { PrismaClient, RoleKey } from '@prisma/client';
import * as argon2 from 'argon2';
import cookieParser from 'cookie-parser';
import request from 'supertest';
import { App } from 'supertest/types';
import { AppModule } from './../src/app.module';

// Admin Users/Roles endpoints + PoliciesGuard (admin-only) over real
// Postgres + Redis. Self-seeds its actors so it doesn't depend on the seed.
describe('Users / RBAC (e2e)', () => {
  let app: INestApplication<App>;
  const prisma = new PrismaClient();

  const adminUsername = 'e2e_admin';
  const opsUsername = 'e2e_ops';
  const password = 'e2e-password-123';
  let adminToken: string;
  let opsToken: string;

  async function ensureRole(key: RoleKey, name: string): Promise<string> {
    const role = await prisma.role.upsert({
      where: { key },
      update: {},
      create: { key, name },
    });
    return role.id;
  }

  async function makeUser(username: string, roleId: string): Promise<void> {
    await prisma.user.deleteMany({ where: { username } });
    await prisma.user.create({
      data: {
        username,
        passwordHash: await argon2.hash(password),
        roles: { create: { roleId } },
      },
    });
  }

  async function login(username: string): Promise<string> {
    const res = await request(app.getHttpServer())
      .post('/auth/login')
      .send({ username, password })
      .expect(200);
    return (res.body as { accessToken: string }).accessToken;
  }

  beforeAll(async () => {
    const adminRoleId = await ensureRole(RoleKey.admin, 'Administrator');
    const opsRoleId = await ensureRole(RoleKey.ops_staff, 'Operations Staff');
    // Ensure the remaining roles exist so GET /roles returns the full set.
    await ensureRole(RoleKey.finance, 'Finance');
    await ensureRole(RoleKey.ops_manager, 'Operations Manager');
    await ensureRole(RoleKey.driver, 'Driver');
    await ensureRole(RoleKey.investor, 'Investor');

    await makeUser(adminUsername, adminRoleId);
    await makeUser(opsUsername, opsRoleId);

    // Clean any users generated by previous runs of this spec.
    await prisma.user.deleteMany({
      where: { username: { startsWith: 'mgomez' } },
    });

    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleFixture.createNestApplication();
    app.use(cookieParser());
    app.useGlobalPipes(
      new ValidationPipe({
        whitelist: true,
        transform: true,
        forbidNonWhitelisted: true,
      }),
    );
    await app.init();

    adminToken = await login(adminUsername);
    opsToken = await login(opsUsername);
  });

  afterAll(async () => {
    await prisma.user.deleteMany({
      where: { username: { startsWith: 'mgomez' } },
    });
    await prisma.user.deleteMany({
      where: { username: { in: [adminUsername, opsUsername] } },
    });
    await prisma.$disconnect();
    await app.close();
  });

  const server = (): App => app.getHttpServer();

  it('rejects unauthenticated access with 401', async () => {
    await request(server()).get('/users').expect(401);
  });

  it('forbids a non-admin (ops) user with 403', async () => {
    await request(server())
      .get('/users')
      .set('Authorization', `Bearer ${opsToken}`)
      .expect(403);
  });

  it('admin creates a user with a generated username (no passwordHash leaked)', async () => {
    const res = await request(server())
      .post('/users')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        fullName: 'Mario Gomez',
        password: 'initial-pass-123',
        roles: [RoleKey.ops_staff],
      })
      .expect(201);

    const body = res.body as { id: string; username: string; roles: string[] };
    expect(body.username).toBe('mgomez');
    expect(body.roles).toEqual([RoleKey.ops_staff]);
    expect(res.body).not.toHaveProperty('passwordHash');
  });

  it('appends a numeric suffix on username collision', async () => {
    const res = await request(server())
      .post('/users')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        fullName: 'Marta Gomez',
        password: 'initial-pass-123',
        roles: [RoleKey.driver],
      })
      .expect(201);
    expect((res.body as { username: string }).username).toBe('mgomez2');
  });

  it('admin lists users without passwordHash', async () => {
    const res = await request(server())
      .get('/users')
      .set('Authorization', `Bearer ${adminToken}`)
      .expect(200);
    const users = res.body as Array<Record<string, unknown>>;
    expect(Array.isArray(users)).toBe(true);
    for (const u of users) {
      expect(u).not.toHaveProperty('passwordHash');
    }
  });

  it("admin replaces a user's roles", async () => {
    const created = await request(server())
      .post('/users')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        fullName: 'Mike Gomez',
        password: 'initial-pass-123',
        roles: [RoleKey.ops_staff],
      })
      .expect(201);
    const id = (created.body as { id: string }).id;

    const updated = await request(server())
      .patch(`/users/${id}/roles`)
      .set('Authorization', `Bearer ${adminToken}`)
      .send({ roles: [RoleKey.finance, RoleKey.ops_manager] })
      .expect(200);

    const roles = (updated.body as { roles: RoleKey[] }).roles;
    expect(roles.sort()).toEqual([RoleKey.finance, RoleKey.ops_manager].sort());
  });

  it('rejects an unknown role on creation with 400-class error', async () => {
    await request(server())
      .post('/users')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        fullName: 'Bad Roleuser',
        password: 'initial-pass-123',
        roles: ['not_a_role'],
      })
      .expect(400);
  });

  it('admin lists all roles', async () => {
    const res = await request(server())
      .get('/roles')
      .set('Authorization', `Bearer ${adminToken}`)
      .expect(200);
    const roles = res.body as Array<{ key: string }>;
    expect(roles.length).toBeGreaterThanOrEqual(6);
    const keys = roles.map((r) => r.key);
    expect(keys).toEqual(
      expect.arrayContaining([RoleKey.admin, RoleKey.finance]),
    );
  });

  it('writes an audit log row for the create', async () => {
    const before = await prisma.auditLog.count({ where: { entity: 'User' } });
    await request(server())
      .post('/users')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({
        fullName: 'Mona Gomez',
        password: 'initial-pass-123',
        roles: [RoleKey.ops_staff],
      })
      .expect(201);
    // Audit write is fire-and-forget; give it a tick to land.
    await new Promise((r) => setTimeout(r, 200));
    const after = await prisma.auditLog.count({ where: { entity: 'User' } });
    expect(after).toBeGreaterThan(before);
  });
});
